### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by joshas** [Postleaf/postleaf#13]
Would be useful to have SQLite support as an alternative to MySQL.

**Comment by claviska** [comment]
I started with flat, then moved to SQLite. My problem with it was the lack of full text search out of the box. They do have two optional full text extensions, but they aren't available on many shared hosts (good luck getting them to recompile to add it) and it requires using virtual tables. Full text in SQLite feels like more of a hack.

I ultimately chose MySQL because it's available almost everywhere PHP is and their full text capability is natively supported :)

**Comment by joshas** [comment]
Good point, never knew about full text search issue with SQLite.
