### ISSUE TITLE
Add system requirements check

### ISSUE THREAD

**Issue by joshas** [Postleaf/postleaf#14]
Before installation installer should check if user has correct PHP version and required extensions, MySQL version and directory permissions.

**Comment by claviska** [comment]
You can find the check for PHP version and extensions in runtime.php. I kept them there in case people try to migrate without running the installer and the checks are negligible in terms of performance.

However, the installer does check permissions by performing a write/read test on all required folders. This only happens initially because it would be a performance hit. :)

**Comment by joshas** [comment]
I initially tried running Postleaf on older PHP version and it would have saved some time if installer warned me about PHP version being too old. Just a nice thing that some other CMSes have.

**Comment by claviska** [comment]
Whoops, the check in `runtime.php` was for 5.4 when it actually requires 5.5+. All fixed for beta2 :)
