### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by joshas** [Postleaf/postleaf#15]
### Issue Summary

Installing Postleaf fails after pressing "Install" button. Installer only populates "_settings" table in database and silently fails, as there are no error messages. Cannot login to admin, because "_user" table is empty.

### Steps to Reproduce

1. Download installer from website (Postleaf 1.0.0-beta1).
2. extract postleaf to webserver and navigate to it's directory using web browser.
3. fill in all required installer fields.

### Additional info

- Postleaf version: Postleaf 1.0.0-beta1
- PHP version: 5.6.18
- Affected browsers: N/A (server side error)
- Operating system: Windows 7 64-bit with Apache 2.4.18

**Comment by claviska** [comment]
Great report. Could you provide the relevant section of your PHP error log? You can delete database.php and rerun the installer if you need to. Thanks!

**Comment by webanvesh** [comment]
Hello,

Same error appears for me too.

**Comment by claviska** [comment]
Hi everyone, if your installation is failing I'll need to see your PHP error log. Thanks!

**Comment by joshas** [comment]
There's a `error_reporting(0);` set in installer.php, that's why I was getting no PHP errors in log.
After setting it to -1 I got some PHP warnings and an Exception:
> PHP Notice:  Undefined index: reset_token in D:\\dev\\UwAmp\\www\\postleaf\\source\\classes\\User.php on line 79, referer: http://localhost/postleaf/source/installer/
> PHP Notice:  Undefined index: bio in D:\\dev\\UwAmp\\www\\postleaf\\source\\classes\\User.php on line 80, referer: http://localhost/postleaf/source/installer/
> PHP Notice:  Undefined index: cover in D:\\dev\\UwAmp\\www\\postleaf\\source\\classes\\User.php on line 81, referer: http://localhost/postleaf/source/installer/
> PHP Notice:  Undefined index: avatar in D:\\dev\\UwAmp\\www\\postleaf\\source\\classes\\User.php on line 82, referer: http://localhost/postleaf/source/installer/
> PHP Notice:  Undefined index: location in D:\\dev\\UwAmp\\www\\postleaf\\source\\classes\\User.php on line 83, referer: http://localhost/postleaf/source/installer/
> PHP Fatal error:  Uncaught exception 'Exception' with message 'Database error: SQLSTATE[HY000]: General error: 1364 Field 'reset_token' doesn't have a default value' in D:\\dev\\UwAmp\\www\\postleaf\\source\\classes\\User.php:126\nStack trace:\n#0 D:\\dev\\UwAmp\\www\\postleaf\\source\\installer\\install.php(213): Postleaf\\User::add('nanoline', Array)\n#1 {main}\n  thrown in D:\\dev\\UwAmp\\www\\postleaf\\source\\classes\\User.php on line 126, referer: http://localhost/postleaf/source/installer/

**Comment by claviska** [comment]
I think you're running MySQL in strict mode. I'll need to update my dev environment to account for that. The problem was that the `reset_token` field wasn't being set in `User::add()` and has been fixed in 756cc79. I've also enabled errors/warnings in e24f97a.

I have a few more things to address today, then I'll put out a patch release with these fixes. You can wait for `1.0.1-beta1` tonight/tomorrow or build it now using the instructions found in the readme. (If you build, make sure to add the [range theme](https://github.com/postleaf/range) to `content/themes/` before running the installer).

If you run into anymore MySQL strict errors, please let me know :)

@webanvesh — if this isn't the same issue you're having, please open a new issue and post your error log.
