### ISSUE TITLE
Frontend admin links has no images on Firefox and IE

### ISSUE THREAD

**Issue by joshas** [Postleaf/postleaf#16]
After logging in as admin, there are two links to admin functions on bottom right of the screen (.pl-home and .pl-new-post).
On Firefox and Internet Explorer images are not displayed:
![capture](https://cloud.githubusercontent.com/assets/79141/17269145/aed2f5b0-5649-11e6-821b-e575c2f3ffcc.PNG)
Firefox complains about "XML Parsing Error: unclosed token, Line Number 1, Column 338".
SVG must be URI encoded, e.g. http://codepen.io/RwwL/pen/Aczds ( encodeURIComponent() + UTF8 SVG with full charset=utf-8 works on all browsers correctly).

**Comment by claviska** [comment]
Looks like IE didn't like the way the SVGs were [not] encoded. I got it working inline in Firefox, but IE still wasn't having it. Then I tried with separate files and they worked fine. Looking at it now, I think it will be more maintainable than having the images inline, and since they only show up when an admin is logged in, I'm OK with the extra HTTP requests.
