### ISSUE TITLE
Errors during install (npm fails)

### ISSUE THREAD

**Issue by venatoria** [Postleaf/postleaf#21]
### Summary

NPM faills.
Attached npm errors log
[npm-debug.log.zip](https://github.com/Postleaf/postleaf/files/956748/npm-debug.log.zip)

  

### Additional info

- Postleaf version:
- Node version:
- Affected browsers:
- Operating system: Ubuntu 16.04

---

Note: This issue tracker is ONLY for bug reports and feature requests. If this is a personal support issue, please ask on the forum instead: community.postleaf.org

**Comment by lukewatts** [comment]
Does this fail when you try running `gulp build` or is it `npm install`?

**Comment by karsasmus** [comment]
You're using node 4.2.6 (`info using node@v4.2.6`), but Postleaf needs node 7

**Comment by venatoria** [comment]
@lukewatts both, if you check the log, errors are generated in both phases. 
@karsasmus I updated and the npm install 
[2017-04-26T09_06_25_854Z-debug.log.zip](https://github.com/Postleaf/postleaf/files/957780/2017-04-26T09_06_25_854Z-debug.log.zip)
still fails, attached the new log

**Comment by lukewatts** [comment]
Personally I had to install gulp, node-gyp and node-pre-gyp globally.

Then I had to rebuild the following packages (e.g. `node rebuild node-sass`):
- node-sass
- optipng-bin
- jpegtran-bin
- sequelize
- sqlite3

**Comment by karsasmus** [comment]
Try to open your `package.json`, goto line 10 and change `install` to `postinstall`

**Comment by venatoria** [comment]
@lukewatts 
@karsasmus 
Hi and thank you for the replies. 
I did what you both recommended.. and the install worked (npm and gulp). 
But the app crashes with the following message : 

Error: Postleaf failed to start! 🐛

SequelizeUniqueConstraintError: Validation error

**Comment by lukewatts** [comment]
I'm also stuck at this point. I've created a separate issue here:

#22

**Comment by venatoria** [comment]
Saw it.. 
I will also see if I can figure it out. 
Any thoughts @claviska ?

**Comment by claviska** [comment]
Isn't `install` and `postinstall` the same thing? [From the npm docs:](https://docs.npmjs.com/misc/scripts)

![screen shot 2017-04-26 at 9 07 46 am](https://cloud.githubusercontent.com/assets/55639/25436343/083b8c5c-2a61-11e7-89f6-b174a978f338.png)

I couldn't find anything that says they're different, and `install` works for me so I'm not entirely sure. 🤷‍♂️ 

As mentioned in #22, I just released [1.0.0-alpha.2](https://github.com/Postleaf/postleaf/releases/tag/1.0.0-alpha.2) which fixes the database issue (see #9).

If you were installing 1.0.0-alpha.1 instead of master, try alpha.2 and it should work. If you _were_ using master, then I'm not sure why it didn't work short of a permissions issue.

Let me know if it works with alpha.2.

**Comment by venatoria** [comment]
@claviska Thanks for the answer.. I will try out alpha2 and see
will keep you posted

**Comment by venatoria** [comment]
Hooray! Working and it's beautiful :) 
@lukewatts, @karsasmus  @claviska thank you <3 

I updated to alpha2 and added (+x to the permission, didn't change the user).
