### ISSUE TITLE
Saving settings goes back to posts list

### ISSUE THREAD

**Issue by jclacherty** [Postleaf/postleaf#31]
When you change a setting then save it, the admin page is redirected to admin/posts instead of staying on the settings page. Occurs when saving on the navigation page also.

**Comment by claviska** [comment]
This was intentional, but it does seem to cause confusion when no feedback is shown. The new behavior shows feedback for every save operation and only redirects when there's a parent page (e.g. Edit Post ==> Posts, Edit User ==> Users, Edit Tag ==> Tag). For Navigation and Settings, the user will not be redirected.

**Comment by jclacherty** [comment]
Thanks. It was a bit of a pain (and unexpected) when I was cycling through the various themes to see what was there.
