### ISSUE TITLE
Animated images render incorrectly when viewed dynamically

### ISSUE THREAD

**Issue by juan-manuel-alberro** [Postleaf/postleaf#44]
### Summary

The GIF images doesn´t work as expected after publish

### Steps to Reproduce

1. Create a new publication
2. Add a GIF and insert it into the publication
3. Save

### Additional info

- Postleaf version: latest version from master
- Node version: 7.9.0
- Affected browsers: alls
- Operating system: macOS Sierra
---
### Demo

![](https://media.giphy.com/media/3oKIPuAClSKQoKQSAM/giphy.gif)

**Comment by claviska** [comment]
Can you attach the original, unmodified image? I'd like to test this with GD.

**Comment by juan-manuel-alberro** [comment]
Is the GIF from the Atom's website, here's the [link](https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/packages@2x-15dd12e2fecd178e33c6324a7e252197.gif).

**Comment by claviska** [comment]
This is an issue with how GraphicsMagick handles animated GIFs. I need to investigate this more, but I believe this option will be helpful: http://www.graphicsmagick.org/GraphicsMagick.html#details-coalesce

We either need to not process animated GIFs or find a reliable way to process them. Also affects Dynamic Images.

**Comment by claviska** [comment]
Found a fix using GM's `coalesce` method, but it deoptimizes frames, resulting in a larger image than the original (in this case, 296KB ==> 5MB). Still looking into options.

**Comment by claviska** [comment]
The best I can do to address this is to simply not process images with animation (see 59921a3). This leaves animations unaltered, but at the expense of not being able to use any Dynamic Images features on them. Unfortunately, this type of processing is just too slow and memory intensive.

One alternative is to use just the first frame of the animation, but that may cause confusion since the original would be animated but modified versions won't.
