### ISSUE TITLE
Problems updating from alpha.4 to alpha.5

### ISSUE THREAD

**Issue by lukewatts** [Postleaf/postleaf#58]
So I decided to try my first update with Postleaf....and things didn't go so well.

I was on version 1.0.0-alpha.4 and after updating to 1.0.0-alpha.5 I simply got this error:

![postleaf-error after-update](https://cloud.githubusercontent.com/assets/4622166/26334288/e5527af6-3f5b-11e7-8582-6c365f803693.png)

I tried also updating the Empower theme to the latest but that didn't fix it.

Luckily, I had backed up my entire site beforehand and I was able to get back to where I was. But I'd certainly like to avail of Sitemaps and JSON feed etc.

### Steps to Reproduce

1. Upgrade from 1.0.0-alpha.4 to 1.0.0-alpha.5 using Empower theme

### Additional info

- Postleaf version: 1.0.0-alpha.4/5
- Node version: 7.9.0
- Affected browsers: N/A
- Operating system: Ubuntu 16.04

**Comment by claviska** [comment]
Uh oh. Did you restart the app? Those are the same steps I use to update the demo and postleaf.org.

That VError is actually from Adaro which was scrapped in alpha 4 and replaced with the custom rendering engine. You sure it was alpha and not 3?

The update process is getting easier but from older versions it might still be tricky.

Also double check your .env file since some changes were made in alpha 3. Compare to the latest in the repo for an example.

**Comment by lukewatts** [comment]
It was alpha.3. My bad. I thought I'd updated to 4 but I hadn't.

This is where that CLI would be real handy. `postleaf -v` and so forth.

I'll have another go in a few days.

**Comment by claviska** [comment]
Sounds good. I'm pretty sure the `.env` file is the culprit here. Feel free to reopen if that doesn't fix it. 😄
